### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by chen-xihui** [ShengrenHou/DRL-for-Energy-Systems-Optimal-Scheduling#5]
Can you upload the code of drawing the results of  training? Such as the mean reward and cost of training, which are shown in your paper.

**Comment by ShengrenHou** [comment]
Hey, you can write by yourself, it is easy. 
After uploading the code, I forgot to keep the local copy of the original figure plotting function, which generated figures for this paper (I usually modify based on my demands for different papers..). Thus, I can not find it and provide it to you.

**Comment by chen-xihui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
