### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by chen-xihui** [ShengrenHou/DRL-for-Energy-Systems-Optimal-Scheduling#9]

**Comment by chen-xihui** [comment]
Look forward to hearing from you.

**Comment by minwabuguai** [comment]
Hi, the author said there are problems with PPO. But seems you have fixed it already. Could you tell me how did you fix it?

**Comment by chen-xihui** [comment]
> Hi, the author said there are problems with PPO. But seems you have fixed it already. Could you tell me how did you fix it?
You can set episode=20000. Even though it can discharge to 0.2, but its cost in a day is far more than MILP in a day.

**Comment by minwabuguai** [comment]
> > Hi, the author said there are problems with PPO. But seems you have fixed it already. Could you tell me how did you fix it?
> > You can set episode=20000. Even though it can discharge to 0.2, but its cost in a day is far more than MILP in a day.
> > By the way, have you ever tried other algorithms? I have tried DDPG, it didn't work either.
> > It's really strange.

Thanks for the info! I am currently running with DDPG and the learning curve looks fine. But I didn't focus on the operation cost. Are you using the data from the author as well?  zhangminvsjoy@gmail.com This is my email if you'd like to have further discussion on this.

**Comment by Liang-335** [comment]
Hello, have you solved this problem? Can you give me your contact information to chat?
